### ISSUE TITLE
Pvp utility

### ISSUE THREAD

**Issue by hasnogaems** [dev7355608/ClassicAggroHighlight#1]
Is it also light up when enemy player targets party member? Is there a way to add a counter of enemys currently targeting party member?

In 5s in tbc atm that would be golden

**Comment by dev7355608** [comment]
I'm not going to add new features to this addon. Surely there must be some addon or Weak Aura out there that does this already.

**Comment by hasnogaems** [comment]
I searched far and wide good sir. Did not found any of neither so far.
