### ISSUE TITLE
Mechanics of this highlights

### ISSUE THREAD

**Issue by hasnogaems** [dev7355608/ClassicAggroHighlight#2]
How exactly those highlights work? When they activated? Is it depends on yout current target? I was trying to get clarification about those long time ago on wowinterface but got none.

**Comment by dev7355608** [comment]
It doesn't depend on the current target. It's based on all mobs the player is in combat with.

```
yellow = has higher than 100% threat on a mob, but isn't the primary target of the mob
orange = is the primary target for a mob, but another unit has higher than 100% threat
red = is the primary target for a mob and no other unit has higher than 100% threat
```

The behavior of this mod was the same as in retail and in WotLK Classic now. It's no longer needed; if fact unnecessary and should be removed. Unfortunately Blizzard forgot to implement a setting to turn these aggro highlights off.
