### ISSUE TITLE
The aggro indicator is sometimes rendering as a very thin border

### ISSUE THREAD

**Issue by aloucks** [dev7355608/ClassicAggroHighlight#3]
As the title states, the aggro indicator is often rendering behind other elements on the frame (e.g. the rage and hp bars), and only a very thin sliver of it is visible around the health box. 

I changed `ARTWORK` to `OVERLAY` on this line and the problem appears to be resolved. I can submit a PR if needed.

https://github.com/dev7355608/ClassicAggroHighlight/blob/8e89c27061e1a225890a8402c6909623c88d2d51/ClassicAggroHighlight.lua#L73

**Comment by dev7355608** [comment]
Thanks! Fixed.
